import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HeaderTop from "../Components/HeaderTop"; 
import HeaderMain from "../Components/HeaderMain"; 
import Navbar from "../Components/Navbar";
import "slick-carousel/slick/slick.css"; 
import "slick-carousel/slick/slick-theme.css";
import { ShopProvider } from "../Context/ShopContext"; // Importar el contexto

// Fuentes
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Ajustar cartItems con las propiedades title y price
  const cartItems = [
    { id: 1, quantity: 2, title: "Jogger Cargo Celeste", price: 401 },
    { id: 2, quantity: 3, title: "Jogger Cargo Verde Militar", price: 304 },
    { id: 3, quantity: 1, title: "Jogger Cargo Celeste Pastel", price: 475 },
  ];

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ShopProvider> {/* Envolver toda la aplicación con el contexto */}
          <HeaderTop />
          <HeaderMain cartItems={cartItems} />
          <Navbar />
          {children}
        </ShopProvider>
      </body>
    </html>
  );
}
